### ISSUE TITLE
Generate doc for service metrics

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1003]
We can generate this information automatically from the source and integrate to our docs. 

https://help.aiven.io/en/articles/5144867-aiven-service-metrics
https://help.aiven.io/en/articles/5144953-additional-service-metrics

**Comment by laysauchoa** [comment]
automation step will be similar to https://github.com/aiven/devportal/pull/945

**Comment by lornajane** [comment]
I'm a little unclear about how this will work, because I assume any script would need access to the core repos, which we don't have from this public repository. Am I missing something here? This might be something to not automate, but to run (at least to start with) locally by a user who has access to both code bases and can specify the path to the internal code repositories.

**Comment by laysauchoa** [comment]
Thanks for bringing this up but the information will be taken from: https://github.com/influxdata/telegraf which is a public repository.  I will summarize here the plan:
1. a command in tegraf will be added to drop the metrics
2. an endpoint will be created that gives the metrics in json format
3. then, we can crawl this in the devportal

**Comment by laysauchoa** [comment]
As information. this PR links the old metrics: https://github.com/aiven/devportal/pull/1198. When this issue #1003 is solved, we need to replace there.

**Comment by laysauchoa** [comment]
To automate this, we need quite some work which unless it is our priority to make this docs automatically and periodically updated regarding this information, then I do not think it seems to be the time for this. Closing due to this.
