### ISSUE TITLE
terraform: warning about the highlights

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1031]
When building with `make livehtml` I get the following error:

```
/Users/laysa.uchoa/Documents/devportal/docs/tools/terraform/reference/cookbook/kafka-flink-integration-recipe.rst:33: WARNING: Could not lex literal_block as "terraform". Highlighting skipped.
/Users/laysa.uchoa/Documents/devportal/docs/tools/terraform/reference/cookbook/kafka-karapace-recipe.rst:25: WARNING: Could not lex literal_block as "terraform". Highlighting skipped.
```

Seems this highlight is not recognized

**Comment by dewan-ahmed** [comment]
Thanks for raising this issue Laysa. A note that I have a ToDo with the warning as part of [this cleanup task](https://github.com/aiven/devportal/issues/959). In case you tackle the warning issue earlier, please let me know and I can update my issue accordingly.

**Comment by laysauchoa** [comment]
Hi @dewan-ahmed, I was thinking to leave this for the upcoming new contributors. wdyt?

**Comment by dewan-ahmed** [comment]
I'll be working on this after the initial goal of 10 Terraform recipes is reached. So I plan to take on this task in the first two weeks of July. Since I used the tool terrafmt that does syntax highlighting, it might make sense for me to tackle this. For new contributor, this might be bit of a challenging task. 

If it's Ok with you, let's close this task. Thanks.

**Comment by dewan-ahmed** [comment]
I'll be working on this after the initial goal of 10 Terraform recipes is reached. So I plan to take on this task in the first two weeks of July. Since I used the tool terrafmt that does syntax highlighting, it might make sense for me to tackle this. For new contributor, this might be bit of a challenging task. 

If it's Ok with you, I'll close this task. Thanks.

**Comment by laysauchoa** [comment]
np :)
