### ISSUE TITLE
Calm down linkchecking

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1038]
Rather than checking all the links on every build (there are a lot now!), it would be ideal if we could:
 * only check changed links
 * do a full link check on a regular (weekly? Like the other automated jobs?) basis so we do pick up if anything on an external site has decayed

**Comment by laysauchoa** [comment]
Going over these points:

1. only check changed links
2. do a full link check on a regular (weekly? Like the other automated jobs?) basis so we do pick up if anything on an external site has decayed

Here are my thoughts:
1) Seems like the only way to run linkcheck is running in all the files. There was a tool at some point that could run on the differences but it is not supported on the latest versions. You can check the info here: https://github.com/sphinx-doc/sphinx/issues/10643#issuecomment-1177956493 

Do you have some ideas what we can try to solve this?

2) Yes, we can do this. Does this depends on point 1) to be done first? Otherwise, I can add a workflow for it.

**Comment by laysauchoa** [comment]
Hi, @lornajane! Thanks for asking more details in how we can solve this here.

I figured out how to run this with GitHub actions. This will reduce the current build time for the checking the links.

-     only check changed links (https://github.com/aiven/devportal/pull/1181)
-     do a full link check on a regular (weekly? Like the other automated jobs?) basis so we do pick up if anything on an external site has decayed

Could you please clarify about the second point, should it be added to the same PR? Thank you!

**Comment by lornajane** [comment]
Yes, let's add the full check as a weekly thing with the other Tuesday jobs, I think it makes sense to put it in the same PR so we keep checking everything until we put in the weekly job setup
