### ISSUE TITLE
SEO: Have more descriptive text  in linktexts

### ISSUE THREAD

**Issue by laysauchoa** [aiven/devportal#1276]
Checking [devportal](https://developer.aiven.io/) website with [Lighthouse tool](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en), we have performed average (83/100) on SEO. To be considered good, we need to be above 90 points. 

These checks ensure that devportal page is following basic search engine optimization advice.

Problem found:
It found 10 links which the link text has not descriptive text. They are all located in the landing page https://developer.aiven.io/

For example:
[…products/postgresql](https://developer.aiven.io/docs/products/postgresql)
(developer.aiven.io)
	Read more

As explained, descriptive link text helps search engines understand your content. You can read more: https://web.dev/link-text/?utm_source=lighthouse&utm_medium=devtools

Proposed solution:
The solution for this is to include some more specific descriptions in the link text. I am adding some proposals here which would make it more specific, but feel free to add your thoughts on how would you solve that.

1) Use service name with logo on the button instead of Read more
<img src="https://user-images.githubusercontent.com/36624597/185863019-ab3dda73-8a73-450e-b344-5a840628ea23.png" width="600" height="350">

2) Use service name without logo on the button instead of Read more. Have logo on the beginning of the box. 
<img src="https://user-images.githubusercontent.com/36624597/185863025-c5d81073-5c75-4d9b-93dc-4c4784f8fb28.png" width="600" height="350">

**Comment by lornajane** [comment]
I would prefer that we do not make this change. If the buttons are confusing our users, let's get some advice from our UX colleagues on what would make this landing page more understandable and inclusive for all.

**Comment by laysauchoa** [comment]
@lornajane would be possible to tag the colleagues that can help us with that? thanks

**Comment by staceysalamon-aiven** [comment]
@lornajane @laysauchoa I'm happy to work on this from a UX copy perspective and discuss with the design team as needed. :)

**Comment by laysauchoa** [comment]
This would be amazing @staceysalamon-aiven thank you so much! I am available for any questions or help from our side.

**Comment by staceysalamon-aiven** [comment]
@laysauchoa @lornajane I think the best option for the product cards might be to change the button text to: "Learn about [PRODUCT]". It's more accessible and better for SEO, but I think also short enough to look okay and be easily scannable.

For the tools, we could do the same thing or have the button text read: "Get started with Aiven CLI" (Same for the API, etc.). This is a little more descriptive and since the main pages have a getting started/quick start section, it seems appropriate. Some of them might be a little long, though.

The Aiven Console is the one exception - we could change this text to: "Launch Aiven Console". But, I'll be adding an Aiven Console overview article soon, so we'll have something for that!

Let me know your thoughts! 🙏

**Comment by staceysalamon-aiven** [comment]
@edithyeghiazaryan Hi! We are looking at updating the button text on [the main page](https://docs.aiven.io/) and would like to get your advice on whether or not this would work from an SEO perspective (or any other thoughts you have)?

- Under Explore, change the button text to: "Learn about PRODUCT" (for example: Learn about PostgreSQL)
- Under Tools, change the button text to: "Get started with TOOL" (for example: Get started with Aiven CLI"
- For the Aiven Console, since we currently link to the web console with that button, change the text to: "Launch Aiven Console"

Hope that makes sense and thanks in advance for your help!

![image](https://user-images.githubusercontent.com/111294980/193277763-e96d881f-80d8-43c7-a435-d4e1e744ba82.png)

![image](https://user-images.githubusercontent.com/111294980/193277804-ed0a4e11-531d-4f88-8df9-a23fffbc594c.png)

**Comment by laysauchoa** [comment]
I also like @staceysalamon-aiven idea. I'm not sure visually how just the link would look like, so I'm more inclined to the descriptive button approach. 

We can continue in the Issue here.

**Comment by staceysalamon-aiven** [comment]
> @staceysalamon-aiven Regarding the buttons, updating the button texts (button anchor text) with more descriptive ones is a very nice idea! The short answer is yes.
> 
> We don’t even need the buttons here. Instead, we could adjust the subheadings and turn them into links/CTAs.
> 
> Here is an SEO brief to optimize the Aiven Documentation page even more by improving the meta data, internal linking, anchor texts, etc. https://www.notion.so/ganztags/Devportal-Homepage-a5fc7333f5834da497c1e9919e7f6902 If you have questions, please let me know.
> 
> Should we open a separate request for this or continue here? @staceysalamon-aiven @laysauchoa @lornajane

Thanks for looking at this! 

I wasn't able to access the Notion page. I got this error: "You do not have access to ganztags.. Please contact an admin to add you as a member."

**Comment by edithyeghiazaryan** [comment]
@staceysalamon-aiven could you please request access? The agency we collaborate with will grant access.

**Comment by staceysalamon-aiven** [comment]
@edithyeghiazaryan Sure, could you DM me an email address? There is no button to do this in the error message, unfortunately. ☹️

**Comment by edithyeghiazaryan** [comment]
@staceysalamon-aiven have you got the access already?

**Comment by staceysalamon-aiven** [comment]
> @staceysalamon-aiven have you got the access already?

No, I'm afraid not.

**Comment by staceysalamon-aiven** [comment]
@edithyeghiazaryan I have access now! I will have a look and let you know of any questions. Thanks!

**Comment by staceysalamon-aiven** [comment]
@edithyeghiazaryan I've had some time to look through the SEO brief this morning and it looks like the recommendation for the button link text was similar to what I put above, at least for the Tools section.

- They mentioned not using "Read more about <product>" because that would also apply to the blog post. If we stick with the button format, do you think "Learn about <product>" is okay then (as in the screenshots in my previous post)? I didn't use something like "PostgreSQL tutorials" since the doc sections we link to have conceptual articles as well as how-tos. Open to other suggestions here!

- For the description of each service/tool, do you have any suggestions for keywords here? I think some of them could be reworded a little (see below), so there may be an opportunity to also improve the SEO there?

- I went ahead and did a quick edit to see what this would look like if we just changed the title of each card into a link. @laysauchoa Would like to hear your thoughts on the visual aspect of this! I also reworded some of the descriptions a little for consistency/tone, but I did not spend a lot of time on this and still think there is room for improvement. 

![image](https://user-images.githubusercontent.com/111294980/198244606-27d588af-a946-4759-8216-4102d4ef08fd.png)

![image](https://user-images.githubusercontent.com/111294980/198244654-aa192f26-c654-467f-9777-166054c86d09.png)

- Note that I've left the button on the Aiven Console card. My thought was that we could link the heading to the new Aiven Console overview page (coming soon!), but still have the button to launch the console itself. But maybe it just looks out of place now?

Thanks!

**Comment by edithyeghiazaryan** [comment]
@staceysalamon-aiven Ganztags mentioned not to leave these buttons as they are now ("Read more" and nothing else) but to put descriptive text there. "Learn about PRODUCT" can work too. The same applies to tools - the idea you initially suggested works.

Not to confuse you; yes, the recommendations from Ganztags were very similar to yours. In other words, all the ideas that you proposed would only positively affect SEO. Therefore,

to answer your initial questions about the buttons' text;

- Under Explore, change the button text to: "Learn about PRODUCT" (for example: Learn about PostgreSQL) - **Yes, it works**

- Under Tools, change the button text to: "Get started with TOOL" (for example: Get started with Aiven CLI" -  **Yes, it works**

- For the Aiven Console, since we currently link to the web console with that button, change the text to: "Launch Aiven Console"-  **Yes, it works**


In addition to all these can we also improve the meta description and meta title of that page?
![image](https://user-images.githubusercontent.com/107199141/198308238-2f3bc60e-beea-428c-b57e-f6d31e4d97f4.png)

**Comment by staceysalamon-aiven** [comment]
@edithyeghiazaryan Thank you for that! I will include the changes to the page title and description in these updates, too.

@laysauchoa Shall we stick with the buttons then and go with the language in the first screenshots I showed above? Also, to change the title and description of this page I am assuming I just need to update the index.html file under _build, is that correct?

**Comment by laysauchoa** [comment]
Hi @staceysalamon-aiven the goal is to help us with the SEO performance, so thanks for bringing the suggestions and for the discussion. The proposal changes will impact the design of the devportal and needs to be discussed with the responsible for that to see if it is okay. I'm not sure who can help us with that.

**Comment by staceysalamon-aiven** [comment]
Thanks @laysauchoa!

@lornajane Could you let me know what you think and what the next steps should be for this? 🙏

**Comment by lornajane** [comment]
With the rebranding going on which impacts how these are presented (existing buttons become action links), let's wait for that to merge and then perhaps @staceysalamon-aiven you can apply the rewordings (both the descriptions and the action links) that are discussed here? I think this brings the best of both words together!

**Comment by staceysalamon-aiven** [comment]
@lornajane That sounds great! Happy to make the content changes when the rebranding is merged.
