### ISSUE TITLE
Migrate article: Automated Debezium Kafka PostgreSQL test environment deployment

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1299]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/5278616

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by bcrisologo** [comment]
@lornajane Where would this article best fit at? It's an integration with 3 services:
- Kafka
- Kafka Connect
- PostgreSQL

It also requires Terraform as well and since it's an automated deployment, I am inclined to place it as a separate page under [Aiven Terraform Provider HowTo](https://docs.aiven.io/docs/tools/terraform/howto.html) section.

Let me know if that sounds good or if it's better placed somewhere else and I can go with that.

**Comment by lornajane** [comment]
@bcrisologo Yes please, the Terraform howto looks like a good place for it! Please verify the steps are still valid by testing the process when migrating.

**Comment by bcrisologo** [comment]
Thanks for this @lornajane! I'll test out the article, but will probably follow the instructions on the [official github repo](https://github.com/aiven/debezium-pg-kafka-connect-test), update that repo to be up-to-date, then migrate the article accordingly with the new changes that makes it work.  I noticed some of the files are outdated at least on the tf side.

**Comment by bcrisologo** [comment]
I haven't been able to successfully complete the automation testing as there were things failing in the script last I tried this out.  I think we should just close this for now as the repo linked in my previous comment hasn't been updated in a while.
