### ISSUE TITLE
Some checks fail for external contributors

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#1480]
We have a known issue related to https://github.com/reviewdog/reviewdog/issues/832 where some checks do not complete for pull requests from external contributors, related to our Vale usage. If this happens, add a comment to your pull request. We will review it in the usual way but will run the checks locally to check that everything is in good shape before merging.

This issue is also here to gather comment and information on fixing this problem.

**Comment by lornajane** [comment]
@laysauchoa I know we talked about this, but did we fix it? Can you put the details here so we can remember next time?

**Comment by laysauchoa** [comment]
There were two things happening around the time this Issue was created:
- GitHub Actions had general problems. Many builds were failing and manually we run them again by force pushing.
- This change was reverted: _**Only admins can merge if the prose build jobs don't pass**_.

This week, an external contributor open a pull request https://github.com/aiven/devportal/pull/1618 and the tests were working fine. So I think this is no longer an issue. 

You can check them in the actions:

<img width="1015" alt="Screenshot 2022-12-08 at 13 51 47" src="https://user-images.githubusercontent.com/36624597/206452029-07d60544-d317-41a7-b394-a65fcc11e5af.png">

**Comment by lornajane** [comment]
Thank you, I knew you would know! I'm going to close this for now, and can re-open if we need to.
