### ISSUE TITLE
wrong link in "Backups at Aiven" page

### ISSUE THREAD

**Issue by kamonspecial** [aiven/devportal#1661]
# What's wrong?

[this](https://docs.aiven.io/docs/platform/concepts/service_backups) page has the wrong link ([periodic cleanup of powered-off services](https://help.aiven.io/en/articles/4578430-periodic-cleanup-of-powered-off-services)). This still refers to [help.aiven.io](http://help.aiven.io/).

# URL of affected page, and any other information

https://docs.aiven.io/docs/platform/concepts/service_backups

**Comment by lornajane** [comment]
Thanks for the report @kamonspecial . Any help.aiven.io pages that now redirect to the docs landing page indicate that there's no replacement content for that topic - with nowhere to link to, we send users to the home page so they can search or navigate from there. Anyone at Aiven can create the documentation, but since the link is not broken, I will close this issue.
