### ISSUE TITLE
Migrate kafka connect terraform integration doc

### ISSUE THREAD

**Issue by ftisiot** [aiven/devportal#464]
# What should we add to our content collections?

Migrate https://help.aiven.io/en/articles/4187903-kafka-connect-terraform-integration

# Is this something you would work on yourself?

[ ] I plan to open a pull request for this

**Comment by dewan-ahmed** [comment]
@ftisiot Would https://developer.aiven.io/docs/products/kafka/kafka-connect/howto be an ideal new home for this article?

**Comment by ftisiot** [comment]
I'm not really sure if this belongs to the kafka connect subtree or the `/docs/tools/terraform` subtree... 

@lornajane what do you think?

**Comment by lornajane** [comment]
I think terraform, we're trying to collect a series of reference implementations and this a really good example. Especially because I think the service integration concept is something we need more content on. Find the issue about terraform for more of an overview of the cookbook format and to link this issue to it (I'm on mobile, sorry). Let's also make sure to put this as a clear resource on the Kafka Connect landing page too, I agree it could go in either place but hoping to keep the tools in their own spaces for the most part
