### ISSUE TITLE
Additional instructions required for specific OS regarding local development setup

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/devportal#489]
# What's wrong?

When setting up the local development environment, I experienced two different types of errors in two different OS.

1. On MacOS Monterey (v12.1), Python 3.8.10 (installed via conda):

`pg_config executable not found` error

[A search](https://stackoverflow.com/questions/33866695/error-installing-psycopg2-on-macos-10-9-5) suggested the following and it worked like a charm:

`brew install postgresql`

2. On Ubuntu 20.04.3 LTS, Python 3.8.10 (installed directly and not via conda):

`make livehtml` command resulted the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'sphinx-build'`

`sphinx-autobuild -h` shows that **sphinx-autobuild** is in the path but `sphinx-build -h` confirms that **sphinx-build** is not in the path. Since the Makefile uses both of them, the user needs to manually install the missing piece. A note that if the python is installed via conda, both **sphinx-build** &  **sphinx-autobuild** are available in the path.
 
# URL of affected page, and any other information

[This](https://github.com/aiven/devportal#local-development) is the affected page/section.

I'm looking for the following feedback:

1. I propose to test the windows OS as well to cover the developer experience as part of the same fix/PR.
2. Since these are specific fixes for specific OS/situations, can they be listed under a separate **Troubleshooting** section rather than crowding [this section](https://github.com/aiven/devportal#local-development)? For example, [this section](https://github.com/aiven/devportal#windows-users) could also go under the **Troubleshooting** section.

Once I get some comments on the above, I can start on the PR. Thanks.

**Comment by laysauchoa** [comment]
I really like the idea of having separated sessions for different OS because when I am debugging something I would go directly to the system that I am using. 

I must to say that I did not had any of the issues listed here but I am using virtualenv to manage my dependencies. I see in the readme also suggest the user to use virtual env and when you do the tests from kind of zero, do you think is a good idea to also use virtual env and see if the same happens? The reason is that I had issues with conda before related to path or dependencies 🙈

**Comment by dewan-ahmed** [comment]
Thanks @laysauchoa on the venv comment. I'll repeat the process following venv and see if that helps.

**Comment by dewan-ahmed** [comment]
Verified that the above issues don't arise when using ``venv``. Closing this issue. Thanks @laysauchoa
