### ISSUE TITLE
Migrate article: Setting up SAML authentication with Azure

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#810]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3557077

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dewan-ahmed** [comment]
Hi @lornajane I see that this issue has an ``SA`` tag. I also see that https://github.com/aiven/devportal/issues/813 is closed since https://github.com/aiven/devportal/pull/1206 was merged.

1. Does https://github.com/aiven/devportal/pull/1206 cover Azure SAML as well?
2. If not, Is there an SA who'll be taking this on?

Since this is one of the high-priority articles to migrate by this month, I'm happy to take it on if no one is assigned already.

**Comment by encima** [comment]
> Hi @lornajane I see that this issue has an `SA` tag. I also see that #813 is closed since #1206 was merged.
> 
> 1. Does [Migrate SAML OneLogin configuration article #1206](https://github.com/aiven/devportal/pull/1206) cover Azure SAML as well?
> 2. If not, Is there an SA who'll be taking this on?
> 
> Since this is one of the high-priority articles to migrate by this month, I'm happy to take it on if no one is assigned already.

Sorry @dewan-ahmed I did not see your comment when I assigned this. Each PR/Issue covers one single IdP so #1206 covers only OneLogin.
