### ISSUE TITLE
Migrate article: Setting up SAML with Auth0

### ISSUE THREAD

**Issue by lornajane** [aiven/devportal#811]
Migrate the content from this article to fit the documentation portal format https://help.aiven.io/en/articles/3808083

(Assign this issue to yourself before you start, and remember to mention the issue number when you open your pull request)

**Comment by dewan-ahmed** [comment]
Hi @lornajane I see that this issue has an ``SA`` tag. I also see that https://github.com/aiven/devportal/issues/813 is closed since https://github.com/aiven/devportal/pull/1206 was merged.

1. Does https://github.com/aiven/devportal/pull/1206 cover Auth0 SAML as well?
2. If not, Is there an SA who'll be taking this on?

Since this is one of the high-priority articles to migrate by this month, I'm happy to take it on if no one is assigned already.

**Comment by encima** [comment]
@dewan-ahmed please do take it on and follow the same format as #1206. It is not the same as all providers have their own quirks/naming conventions
