### ISSUE TITLE
SEO related: canonical tags of 44 URLs need to be replaced 

### ISSUE THREAD

**Issue by edithyeghiazaryan** [aiven/devportal#934]
**The issue**: The canonical tags of 44 URLs are pointing to redirected pages. As a result, search engines fail to crawl and index the pages properly. https://docs.google.com/spreadsheets/d/13ILZY5Hh3CyuwX3qNlAn-hyEpr-HN0iDMHUL9FBzr74/edit#gid=0

**The solution**: To replace the current canonical URLs with self-referencing canonical tags.

_If additional info is needed, please let me know._

**Resources to look at:** 

**1. Previous discussions on slack:** https://aiven-io.slack.com/archives/C01SY3QU54P/p1654697321714689

Also, Angeline suggests: _"we can use Netlify redirect for the issue with index.html (row 23-44) 
But there is also this sitemap that has index.html and .html in all places https://developer.aiven.io/sitemap.xml -> this can also be configure i assume"_

**2.Educational useful materials:**

- Canonical tags: https://www.semrush.com/blog/canonical-url-guide/?kw=&cmp=DE_SRCH_DSA_Blog_Core_BU_EN&label=dsa_pagefeed&Network=g&Device=c&utm_content=515771357185&kwid=dsa-1057183191115&cmpid=11794204941&agpid=114887190419&BU=Core&extid=23661292104&adpos=&gclid=CjwKCAjw14uVBhBEEiwAaufYx7izGDIDsuLlNGvFyz9l24yrht5c5sqRK1JtFhkiLJCA4aONTJZHmBoCLMMQAvD_BwE

- Redirection - https://djtechblog.com/seo/redirect-default-index-html-to-root-seo-basics/#:~:text=In%20simple%20words%20we%20should,should%20always%20redirect%20to%20root

**Comment by anelook** [comment]
@edithyeghiazaryan, one clarifying question -  "fail to crawl and index the pages properly" - what do we mean by "properly" here? are they ignored completely go google search engine?

**Comment by edithyeghiazaryan** [comment]
@anelook 
Olena, thank you for the question. From the crawlers’ perspective, these pages are canonicalized to non-indexable URLs, which is a paradox for them. As a result, the rankings, impressions, and clicks will drop for these pages if they haven’t dropped already.

Let me give more info; Crawlers assign crawl budget (time) to websites because they don't have unlimited resources. To benefit from this situation, our goal is to help crawlers find and understand our indexable pages as many and quickly as possible and not face barriers during that process (such as now). For that, we need to eliminate the technical issues (part of tech SEO), optimise the content and keywords (on-site SEO) and increase the authority of our website (off-site SEO). If all these problems are solved and opportunities are grabbed, we witness better ranking on search engines, can be easily found by users on diff. search engines, beat our competition easily, get higher clicks and conversion etc. So, these are the goals we are trying to achieve. I hope I could answer your question :))

**Comment by anelook** [comment]
Findings after looking into the issue deeper.

**Different scenarios and behaviours:**

1. Every page can be accessed using suffix .html. When accessing following pages
- https://developer.aiven.io/docs/products/opensearch/index.html
- https://developer.aiven.io/docs/products/m3db/index.html
- https://developer.aiven.io/docs/products/opensearch/index.html
will work without redirects, no 301

2. When accessing the root folder, the server recognises that we look for index.html and returns us correct page, for example
- https://developer.aiven.io/docs/products/opensearch/
- https://developer.aiven.io/docs/products/m3db/
- https://developer.aiven.io/docs/products/opensearch/
will work without redirects, no 301

3.  "index" without ".html" is not a valid page name and the server will need to redirect. This seems to rely currently on Netlify functionality, because when running locally, or in sphinx-docs website (https://www.sphinx-doc.org/en/master/usage/index.html) entering path without ".html" will return 404: Not Found

My understanding that our issue comes from the fact that we use pages without ".html" suffix as canonical links. for example 
 `<link rel="canonical" href="https://developer.aiven.io/docs/products/clickhouse/index" />` These pages are not canonical. This setting comes from `_templates/base.html`

**Possible solutions:** 

1. Taking the example from https://www.sphinx-doc.org/ (reference - https://github.com/sphinx-doc/sphinx/blob/5.x/sphinx/themes/basic/layout.html)we can change the template from `<link rel="canonical" href="https://developer.aiven.io/{{ pagename }}" />` to `<link rel="canonical" href="{{ pageurl }}" />`. This gives a proper url of the page with `.html`. Works for both "/index.html" and "/" and always sets canonical to "/index.html".
However, the problem of this solution - Google will need to reindex all our pages again, because they all already indexed without ".html".

2. Use the solution of @ftisiot  to exclude "index" for all our "index" pages. This is more difficult to maintain and potentially error prone, but this will be aligned with how Google already indexed all the pages.

3. @lornajane let's discuss this as well, I'm curious if you might have other ideas how to approach this :)

**Comment by lornajane** [comment]
I intentionally indexed without the .html because I don't think it makes the URLs easier for people to read, so it was a UX decision - I didn't realise that the index pages were special. I wondered if we could stop using index pages altogether and have, for example in `/docs/products` both the landing page `clickhouse.rst` for a URL of `/clickhouse` and then the pages inside a `clickhouse/` directory as we do now. The concept/howto/reference sections work with way with same-named pages and directories, and don't seem to display the same problem. I am not clear if this would be an option though.

**Comment by anelook** [comment]
@lornajane you suggestion will fix current SEO issue. However, this solution will mean that 

http://127.0.0.1:8000/docs/products/kafka/kafka.html <- will work
http://127.0.0.1:8000/docs/products/kafka/ <- won't work any more by default 

And I think this is inconvenient for users, when we open a folder we want to redirect to the main page of it. 

Possibly it can be changed with Netlify settings so that default page to open no longer index, but the page with the same name as the folder? But this will require additional logic we need to support later.

Also, many would expect index to be main page of the folder, this change might add confusion.
@edithyeghiazaryan , do you know if search engines treat "index" pages differently and if there are any other risks if we rename them?

**Comment by edithyeghiazaryan** [comment]
@anelook  Search engines do not care much about the endings a URL has. 
However, if we make a URL structure change now, it will be considered a website restructuring. This means crawlers need to reindex those pages, which will take time. Meanwhile, we will have traffic drop (highly not desirable). Moreover, that kind of URL structure is not UX friendly. Therefore, the best approach would be to keep the current URLs as they are now (Column B https://docs.google.com/spreadsheets/d/13ILZY5Hh3CyuwX3qNlAn-hyEpr-HN0iDMHUL9FBzr74/edit#gid=0) and change only the canonical tags.

**Comment by edithyeghiazaryan** [comment]
@anelook  Search engines do not care much about the endings a URL has. 
However, if we make a URL structure change now, it will be considered a website restructuring. This means crawlers need to reindex those pages, which will take time. Meanwhile, we will have traffic drop (highly not desirable). Moreover, that kind of URL structure is not UX friendly. Therefore, the best approach would be to keep the current URLs as they are now (Column B https://docs.google.com/spreadsheets/d/13ILZY5Hh3CyuwX3qNlAn-hyEpr-HN0iDMHUL9FBzr74/edit#gid=0) and change only the canonical tags.

**Comment by anelook** [comment]
@edithyeghiazaryan for me it feels that in the column B we should have URL with full path to the file, meaning all files with + "index.html", for example `https://developer.aiven.io/docs/products/postgresql/index.html` <- this is the real full URL.

**Comment by edithyeghiazaryan** [comment]
@anelook If this is the real full URL https://developer.aiven.io/docs/products/postgresql/index.html
we have no issue keeping it.

Overall we need to consider the following things; 
1. keeping only one version of the URL, the other one should be redirected. 1 URL = 1 piece of content otherwise duplication is created. (https://developer.aiven.io/docs/products/postgresql/ should be 301 redirected to the above-mentioned one if we decide to keep that one)
2. every URL should contain a self-canonical tag
3. keeping the number of redirects as low as possible and not create redirect chains (https://www.contentkingapp.com/academy/redirects/faq/redirect-chains/ )

**Comment by anelook** [comment]
Regarding 1. - Redirection is not needed in this case.  "https://developer.aiven.io/docs/products/postgresql/" is the same as "https://developer.aiven.io/docs/products/postgresql/index.html". Both will show same canonical URL (if you check their source code), there is no redirection there - the web server is smart enough to know that when we open  the folder "https://developer.aiven.io/docs/products/postgresql/" we mean that we want to see a default page inside it (usually index.html) "https://developer.aiven.io/docs/products/postgresql/index.html"

**Comment by anelook** [comment]
The current flow seem to be tangled with behaviour of Netlify.  When not using the server, opening a page without ".html" leads to 404. 
To see it, you can run the developer portal locally and try opening 
http://127.0.0.1:8000/docs/products/postgresql/index -> 404
http://127.0.0.1:8000/docs/products/clickhouse/getting-started -> 404

Because we're moving away from Netlify, we need to understand if the current flow will continue to be supported. This can influence which of the solutions we need to use.

@angelinekwan, do you know by any chance what settings in Netlify are responsible for default directory listing (where it is set to use index.html)? Maybe there we have also a setting which redirects "index" to "/"?

**Comment by anelook** [comment]
@lornajane, related to our conversation on Friday, I found a long thread on quora about including or excluding ".html" from SEO urls. Supports your reasoning that generally doesn't give any advantage  -  https://www.quora.com/Is-it-beneficial-for-SEO-to-end-URLs-with-html

**Comment by edithyeghiazaryan** [comment]
@anelook If we do not put a redirection, then both pages will continue to rank as it is happening now (status 200), resulting in a duplication issue. 
Please see the screenshot illustrating that both pages are generating traffic currently. Any thoughts?
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/107199141/174819725-d4c1daa6-83d8-41cd-bd55-7566ee4e892e.png">

**Comment by anelook** [comment]
@edithyeghiazaryan  Adding an artificial redirection (with 301) from https://developer.aiven.io/docs/products/postgresql/index.html  to https://developer.aiven.io/docs/products/postgresql/ feels to be wrong to be honest. Maybe it fixes SEO, but it delays the page load  and requires a separate request that is not needed. 

I also wonder if the number for "https://developer.aiven.io/docs/products/postgresql/" will go down if we remove redirects from "https://developer.aiven.io/docs/products/postgresql/index" to "https://developer.aiven.io/docs/products/postgresql/".

**Comment by edithyeghiazaryan** [comment]
@anelook It's vice versa, putting 301 from https://developer.aiven.io/docs/products/postgresql/ to https://developer.aiven.io/docs/products/postgresql/index.html  since you mentioned in previous messages that the latter is the real full URL.

The idea is to have only one version of the URL (1 URL=1 piece of content, and the URL structure's ending doesn't matter for this case). This is not only for the SEO but for you or other team members as well; in the future, when you link any content to this URL, it will be easier to know which URL to link to since there will be only one version instead of 2. 

Moreover, if you have these backlinks divided between 2 versions of the same page (e.g. you create a piece of content and link to https://developer.aiven.io/docs/products/postgresql/, another person creates another content and links to https://developer.aiven.io/docs/products/postgresql/index.html), then the page authority for these pages won't increase as it supposes to, affecting the webpages' rankings negatively.

Then, since the rel=:canonical" attribute is a hint, not a directive, they may be ignored by search engines resulting cannibalization issue. It means that both pages compete with each other resulting a traffic drop. 

***

Regarding the speed - Please let me know how you think it will affect for each page and after which exact actions? This is how I see the picture; 
the https://developer.aiven.io/docs/products/postgresql/  will be disappeared after some time from the search engines, 
https://developer.aiven.io/docs/products/postgresql/index.html will not have any changes regarding the speed. If there is anything else that doesn't come to my mind, please let me know.

***

Regarding being right from the SEO perspective but not suitable from a technical standpoint - both of their goals are the same - to be present on search engines properly (eventually, our target audience finds the content on google search engine). Thus, following their documentation/rules should not be wrong, I believe. 

Sending you some useful documentation from Google on how websites need to be structured technically correct so that it doesn't harm the overall website.
https://developers.google.com/search/docs/advanced/guidelines/duplicate-content 
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls

***

Regarding your last question - I don't follow, which redirect? Please paraphrase it if I haven't covered the answer in this message yet.

**Comment by anelook** [comment]
@edithyeghiazaryan, taking example from https://developers.google.com/ 
- they have both https://developers.google.com/search/index.html and https://developers.google.com/search/ and there is no redirections between those pages even though they have the same canonical url. They both point to the same resource. Does it mean they also do it incorrectly?

**Comment by lornajane** [comment]
Let's stick to the topic. Thanks @edithyeghiazaryan for the explanation of what's needed. We'll work on this when we can and keep you posted!

**Comment by edithyeghiazaryan** [comment]
@lornajane @anelook Thank you for the updates! Everything looks good, except these 2 links.

- https://developer.aiven.io/index.html
- https://developer.aiven.io/

Could you also please 

- put a 301 redirect **from** https://developer.aiven.io/index.html **to** https://developer.aiven.io/ 
- put a self-canonical tag on the https://developer.aiven.io/  

I will send the rest of the URLs to get indexed.

**Comment by anelook** [comment]
I indeed left one index page  - https://developer.aiven.io/index.html, as I couldn't come up with a good alternative name for it.
@lornajane what's your opinion? should we replace "index" with "main"? I can also add a redirect from  https://developer.aiven.io/index.html to  https://developer.aiven.io/, which will be much cleaner for a starting page. Though I'm not really happy with adding extra redirect for SEO only.

**Comment by anelook** [comment]
@edithyeghiazaryan, we covered 43 links as part of the merged PR. 

The landing index.html has to be solved differently.  I'd suggest that we close this ticket and create a specific one for https://developer.aiven.io/index.html and https://developer.aiven.io/ ? This will make it easier to organise the work and keep an eye on this part.
